### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by mejohnny** [PaulGregor/python-btc-miner#1]
Having trouble with the : 
C:\python-btc-miner-master>pip install requirements.txt
Collecting requirements.txt
  Could not find a version that satisfies the requirement requirements.txt (from
 versions: )
No matching distribution found for requirements.txt

What should I do?

**Comment by PaulGregor** [comment]
Hello. Sorry to inform you, but this repository doesn't contained any working package, so you cannot install it. I created it for solo purpose, maybe some day, I'll finish it =)
